"""empty message

<<<<<<< HEAD:migrations/versions/3ad494b24f94_.py
Revision ID: 3ad494b24f94
Revises: 171983851788
Create Date: 2023-11-26 23:00:51.768255
=======
<<<<<<<< HEAD:migrations/versions/23ff99109d9f_.py
Revision ID: 23ff99109d9f
Revises: e5fa24c72861
Create Date: 2023-11-28 19:27:37.263518
========
Revision ID: 9243a0639b72
Revises: 61ad0906d7ae
Create Date: 2023-11-22 22:53:14.923410
>>>>>>>> 18dcec07105a3a1ae4a1765f2105588976eaf8b0:migrations/versions/9243a0639b72_.py
>>>>>>> 23cbafa89344f2a5b91e0ba972e1cc0309648807:migrations/versions/9243a0639b72_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/3ad494b24f94_.py
revision = '3ad494b24f94'
down_revision = '171983851788'
=======
<<<<<<<< HEAD:migrations/versions/23ff99109d9f_.py
revision = '23ff99109d9f'
down_revision = 'e5fa24c72861'
========
revision = '9243a0639b72'
down_revision = '61ad0906d7ae'
>>>>>>>> 18dcec07105a3a1ae4a1765f2105588976eaf8b0:migrations/versions/9243a0639b72_.py
>>>>>>> 23cbafa89344f2a5b91e0ba972e1cc0309648807:migrations/versions/9243a0639b72_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

<<<<<<<< HEAD:migrations/versions/23ff99109d9f_.py
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('recovery_code')

========
>>>>>>>> 18dcec07105a3a1ae4a1765f2105588976eaf8b0:migrations/versions/9243a0639b72_.py
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/23ff99109d9f_.py
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_code', sa.INTEGER(), autoincrement=False, nullable=True))

========
>>>>>>>> 18dcec07105a3a1ae4a1765f2105588976eaf8b0:migrations/versions/9243a0639b72_.py
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
