"""empty message

Revision ID: 632403719b2d
Revises: 9a4a6a4aca9c
Create Date: 2023-12-01 06:05:10.183978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632403719b2d'
down_revision = '9a4a6a4aca9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
