"""empty message

Revision ID: 88675695c33a
Revises: 63857381033e
Create Date: 2023-12-10 18:57:58.709192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88675695c33a'
down_revision = '63857381033e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
