"""empty message

Revision ID: fc4b67fab724
Revises: 632403719b2d
Create Date: 2023-12-01 17:55:37.133925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4b67fab724'
down_revision = '632403719b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_column('pet_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
